# Generated by Django 5.0.6 on 2024-07-01 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth0_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('api_key_encrypt', models.CharField(max_length=255, unique=True)),
                ('api_key_hash', models.CharField(max_length=255, unique=True)),
                ('api_secret_encrypt', models.CharField(max_length=255, unique=True)),
                ('api_secret_hash', models.CharField(max_length=255, unique=True)),
                ('api_secret_salt', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
