# Generated by Django 5.0.6 on 2024-07-31 19:50

import django.db.models.deletion
import uuid
import whistle.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField()),
                (
                    "first_name",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/28ec4e49-6a91-4994-9e29-dcc2242b597f",
                        null=True,
                    ),
                ),
                ("first_name_hash", models.CharField(null=True)),
                (
                    "last_name",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/28ec4e49-6a91-4994-9e29-dcc2242b597f",
                        null=True,
                    ),
                ),
                ("last_name_hash", models.CharField(null=True)),
                (
                    "email",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/28ec4e49-6a91-4994-9e29-dcc2242b597f"
                    ),
                ),
                ("email_hash", models.CharField()),
                (
                    "phone",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/28ec4e49-6a91-4994-9e29-dcc2242b597f",
                        null=True,
                    ),
                ),
                ("phone_hash", models.CharField(null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("organization", "email_hash"),
                    ("organization", "external_id"),
                    ("organization", "phone_hash"),
                },
            },
        ),
        migrations.CreateModel(
            name="ExternalUserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(unique=True)),
                (
                    "platform",
                    models.CharField(choices=[("IOS", "IOS"), ("ANDROID", "ANDROID")]),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="external_user.externaluser",
                    ),
                ),
            ],
        ),
    ]
