# Generated by Django 5.0.6 on 2024-07-29 22:31

import django.db.models.deletion
import uuid
import whistle.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "EMAIL"), ("PUSH", "PUSH")]
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("TWILIO", "TWILIO"),
                            ("SENDGRID", "SENDGRID"),
                            ("APNS", "APNS"),
                            ("FCM", "FCM"),
                        ]
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider")},
            },
        ),
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "value",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/b85dc402-f251-4563-871b-b7e13812b50e"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="provider.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "slug")},
            },
        ),
    ]
