# Generated by Django 5.0.6 on 2024-07-29 22:31

import django.db.models.deletion
import uuid
import whistle.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property", models.CharField()),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("GT", "GT"),
                            ("LT", "LT"),
                            ("GTE", "GTE"),
                            ("LTE", "LTE"),
                            ("EQ", "EQ"),
                            ("NEQ", "NEQ"),
                            ("CONTAINS", "CONTAINS"),
                            ("DOES_NOT_CONTAIN", "DOES_NOT_CONTAIN"),
                        ]
                    ),
                ),
                (
                    "value",
                    whistle.fields.EncryptedField(
                        key_id="arn:aws:kms:us-east-1:000000000000:key/b85dc402-f251-4563-871b-b7e13812b50e"
                    ),
                ),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="audience.audience",
                    ),
                ),
            ],
            options={
                "unique_together": {("audience", "property")},
            },
        ),
    ]
