# Generated by Django 5.0.6 on 2024-07-23 02:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clerk_user_id", models.CharField(max_length=255, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
