# Generated by Django 5.0.6 on 2024-08-04 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("external_user", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_id", models.UUIDField(unique=True)),
                ("category", models.SlugField(null=True)),
                ("topic", models.CharField(null=True)),
                ("title", models.CharField()),
                ("content", models.CharField()),
                ("action_link", models.CharField(null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("schedule_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "SCHEDULED"),
                            ("QUEUED", "QUEUED"),
                            ("PROCESSED", "PROCESSED"),
                            ("FAILED", "FAILED"),
                        ]
                    ),
                ),
                ("sent_at", models.DateTimeField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("PROCESSED", "PROCESSED"),
                            ("FAILED", "FAILED"),
                        ]
                    ),
                ),
                ("clicked_at", models.DateTimeField(null=True)),
                ("seen_at", models.DateTimeField(null=True)),
                ("read_at", models.DateTimeField(null=True)),
                ("archived_at", models.DateTimeField(null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notification.broadcast",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="external_user.externaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "IN_APP"),
                            ("EMAIL", "EMAIL"),
                            ("SMS", "SMS"),
                            ("PUSH", "PUSH"),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, null=True)),
                ("content", models.CharField(blank=True, null=True)),
                ("action_link", models.CharField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "DELIVERED"),
                            ("ATTEMPTED", "ATTEMPTED"),
                            ("UNDELIVERED", "UNDELIVERED"),
                            ("NOT_SENT", "NOT_SENT"),
                        ]
                    ),
                ),
                ("error_reason", models.CharField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="notification.notification",
                    ),
                ),
            ],
        ),
    ]
