"""
Django settings for whistle project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
from pathlib import Path
from socket import gethostbyname, gethostname

import sentry_sdk
from dotenv import load_dotenv, find_dotenv
from kombu import Queue, Exchange

load_dotenv(find_dotenv())

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", ",").split(",")
ALLOWED_HOSTS.append(gethostbyname(gethostname()))

ENVIRONMENT = os.environ.get("ENVIRONMENT")
SENTRY_DSN = os.environ.get("SENTRY_DSN")

if ENVIRONMENT and SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.25 if ENVIRONMENT == "PROD" else 1.0,
        profiles_sample_rate=0.10 if ENVIRONMENT == "PROD" else 1.0,
        environment=ENVIRONMENT,
    )

INSTALLED_APPS = [
    "notification",
    "external_user",
    "preference",
    "subscription",
    "organization",
    "user",
    "realtime",
    "audience",
    "provider",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "channels",
    "health_check",
    "drf_spectacular",
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("CHANNELS_REDIS", "redis://127.0.0.1:6379/0")],
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "EXCEPTION_HANDLER": "whistle.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "whistle.extensions.CustomOpenApiSettings",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Whistle API",
    "DESCRIPTION": "REST API for the Whistle notification platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "PREPROCESSING_HOOKS": ["whistle.extensions.preprocess_endpoints"],
}

ROOT_URLCONF = "whistle.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
            "propagate": False,
        },
    },
}

WSGI_APPLICATION = "whistle.wsgi.application"

ASGI_APPLICATION = "whistle.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("SQL_DATABASE", "whistle_db"),
        "USER": os.environ.get("SQL_USER", "postgres"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "postgres"),
        "HOST": os.environ.get("SQL_HOST", "127.0.0.1"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
        "CONN_MAX_AGE": os.environ.get("SQL_CONN_MAX_AGE", 300),
        "OPTIONS": {"sslmode": os.environ.get("SQL_SSL_MODE", "disable")},
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_ACKS_LATE = True
CELERY_REJECT_ON_WORKER_LOST = True
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0"
)
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True
CELERY_TASK_QUEUES = (
    Queue("celery", Exchange("celery"), "celery"),
    Queue("broadcasts", Exchange("broadcasts"), "broadcasts"),
    Queue("notifications", Exchange("notifications"), "notifications"),
    Queue("outbound", Exchange("outbound"), "outbound"),
    Queue("dead_letter", Exchange("dead_letter"), "dead_letter"),
)
CELERY_RETRY_BACKOFF = os.getenv("CELERY_RETRY_BACKOFF", 30)
CELERY_BACKOFF_MAX = os.getenv("CELERY_BACKOFF_MAX", 180)
CELERY_RETRY_JITTER = bool(os.getenv("CELERY_RETRY_JITTER", 1))

CELERYBEAT_SCHEDULER = "redbeat.RedBeatScheduler"
CELERY_BEAT_MAX_LOOP_INTERVAL = 5
REDBEAT_LOCK_TIMEOUT = CELERY_BEAT_MAX_LOOP_INTERVAL + 60
REDBEAT_REDIS_URL = os.environ.get("REDBEAT_REDIS_URL", "redis://127.0.0.1:6379/0")

JWKS_ENDPOINT_URL = os.getenv("JWKS_ENDPOINT_URL")

KMS_PERSONAL_DATA_KEY_ARN = os.environ["KMS_PERSONAL_DATA_KEY_ARN"]
KMS_API_CREDENTIALS_KEY_ARN = os.environ["KMS_API_CREDENTIALS_KEY_ARN"]
KMS_CACHE_CAPACITY = os.getenv("KMS_CACHE_CAPACITY", 100)
KMS_CACHE_EXPIRY = os.getenv("KMS_CACHE_EXPIRY", 1800.0)

USE_SENDGRID_SANDBOX = bool(os.getenv("USE_SENDGRID_SANDBOX", 0))
