# Generated by Django 5.0.6 on 2024-07-02 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("external_user", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.SlugField(blank=True, null=True)),
                ("topic", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                (
                    "action_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="external_user.externaluser",
                    ),
                ),
            ],
        ),
    ]
