# Generated by Django 5.0.6 on 2024-07-26 02:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import whistle_server.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "first_name",
                    whistle_server.utils.EncryptedField(
                        blank=True, key_id="alias/PersonalData", max_length=255
                    ),
                ),
                (
                    "last_name",
                    whistle_server.utils.EncryptedField(
                        blank=True, key_id="alias/PersonalData", max_length=255
                    ),
                ),
                (
                    "email",
                    whistle_server.utils.EncryptedField(
                        key_id="alias/PersonalData", max_length=255
                    ),
                ),
                (
                    "phone",
                    whistle_server.utils.EncryptedField(
                        blank=True, key_id="alias/PersonalData", max_length=255
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("organization", "email"),
                    ("organization", "external_id"),
                    ("organization", "phone"),
                },
            },
        ),
        migrations.CreateModel(
            name="ExternalUserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bundle_id", models.CharField(blank=True, unique=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "IOS"), ("ANDROID", "ANDROID")], max_length=255
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="external_user.externaluser",
                    ),
                ),
            ],
        ),
    ]
