# Generated by Django 5.0.6 on 2024-07-26 15:31

import django.db.models.deletion
import uuid
import whistle_server.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clerk_org_id", models.TextField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationCredentials",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="organization.organization",
                    ),
                ),
                (
                    "api_key",
                    whistle_server.utils.EncryptedField(key_id="alias/APICredentials"),
                ),
                ("api_key_hash", models.TextField(unique=True)),
                (
                    "api_secret",
                    whistle_server.utils.EncryptedField(key_id="alias/APICredentials"),
                ),
                ("api_secret_hash", models.TextField(unique=True)),
                ("api_secret_salt", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
        ),
    ]
