# Generated by Django 5.0.6 on 2024-07-03 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clerk_org_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("api_key_encrypt", models.CharField(max_length=255, unique=True)),
                ("api_key_hash", models.CharField(max_length=255, unique=True)),
                ("api_secret_encrypt", models.CharField(max_length=255, unique=True)),
                ("api_secret_hash", models.CharField(max_length=255, unique=True)),
                ("api_secret_salt", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
        ),
    ]
