name: Deploy Websockets

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: ./.github/workflows/base/deploy-to-ecs.yaml
    with:
      service: websockets
      version: ${{ github.event.release.tag_name }}