name: Deploy to Amazon ECS


on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
      iam_role:
        description: 'IAM Role to Assume'
        required: true
      repository:
        description: "ECR Repository"
        required: true
      service:
        description: "ECS Service"
        required: True
      cluster:
        description: "ECS Cluster"
        required: True
      task_definition:
        description: "ECS Task Definition"
        required: True
      container:
        description: "Container Name"      
        required: True
                                               
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event.inputs.iam_role }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Fill in the Image in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ github.event.inputs.task_definition }}
          container-name: ${{ github.event.inputs.container }}
          image: ${{ github.event.inputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
