name: Deploy API

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: ./github/actions/deploy-to-ecs.yaml
    with:
      service: api
      version: ${{ github.event.release.tag_name }}
