name: Deploy Worker

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-ecs.yaml
    with:
      service: worker
      version: ${{ github.event.release.tag_name }}