name: Deploy Websockets

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to ECS
        uses: ./github/actions/deploy-to-ecs.yaml
        with:
          service: websockets
          version: ${{ github.event.release.tag_name }}