name: Deploy Scheduler

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-ecs.yaml
    with:
      service: scheduler
      version: ${{ github.event.release.tag_name }}